version: "3.7"
services:
    cart_api:
        container_name: cart_api
        build:
            context: .
        env_file:
            - .env
        networks:
            - my_network
        ports:
            - 5002:5002
        depends_on:
            - cart_db
    cart_db:
        container_name: cart_db
        networks:
            - my_network
        env_file:
            - .env
        ports:
            - 6378:6378
        image: redis:alpine

networks:
    my_network:
        driver: bridge